name: Vercel Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: 'notify vercel'
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: Vercel - antenna-gui: lint
